version: "3.9"
services:
  dev:
    image: sehandev/lambda-stack:20.04
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /home/wd60/data:/workspace/data
    environment:
      - TZ=Asis/Seoul
      - DEBIAN_FRONTEND=noninteractive
      - JUPYTER_ENABLE_LAB=yes
    shm_size: "8gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    stdin_open: true
  
